server:
  port: 8080

mybatis:
  mapper-locations: classpath:com/bhcloud/jeefast/modules/**/mapper/*.xml
  type-aliases-package: com.bhcloud.jeefast.moudles
  config-location: classpath:mybatis/mybatis-config.xml

spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    encoding: UTF-8
  profiles:
    active: dev

#J2cahce缓存框架
j2cache:
  config-location: classpath:/j2cache.properties
  open-spring-cache: true
  redis-client: lettuce

#日志
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
#    console: "%d - %msg%n"   #日志输出格式
  file:
    name: jeefast.log
    path: ../logs/jeefast/
  level:
#    root: warn
    com.bhcloud.jeefast: debug

#数据库分页插件
pagehelper:
  helper-dialect: mysql  #使用哪种数据库语言
  reasonable: true      #配置分页参数合理化功能，默认是false。 #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页； #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
  support-methods-arguments: true  #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  page-size-zero: true   #当pageSize=0时不进行分页,注意返回的仍是pageInfo类型


#自定义属性
adminPath: /admin
