spring:
  datasource:
    username: root
    password: Rj2fmOU6QZw6YPRIEslpW6W0807
    url: jdbc:mysql://39.108.12.84:3307/liangshan_cloud_dev?useUnicode=true&characterEncoding=utf-8mb4&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
